name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  # cancel jobs on PRs only
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create empty custom.properties
        working-directory: ./quick-start
        run: touch custom.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
         build-root-directory: ./quick-start

      - name: Build with Gradle
        working-directory: ./quick-start
        run: ./gradlew build